# Generated by Django 6.0.4 on 2026-07-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_address_city_user_address_line1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='public_display_name',
            field=models.CharField(blank=True, help_text='Shown on leaderboards / Wall of Honour instead of the real username. Blank = not shown.', max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='checklist_public',
            field=models.BooleanField(default=False, help_text="Opt-in: show this customer's checklist completion on leaderboards and the Wall of Honour."),
        ),
    ]
