# Generated by Django 6.0.4 on 2026-08-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_checklist_public_user_public_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='community_profile_public',
            field=models.BooleanField(default=False, help_text="Opt-in: show this customer's Pokedex collection and wishlist on a public community profile page."),
        ),
        migrations.AddField(
            model_name='user',
            name='community_bio',
            field=models.CharField(blank=True, help_text='Short public note shown on the community profile, e.g. "Looking for shiny Charizards!"', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='messaging_enabled',
            field=models.BooleanField(default=False, help_text="Opt-in: allow other customers to send this customer direct messages / trade requests."),
        ),
    ]
