# Generated by Django 6.0.4 on 2026-09-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_community_profile_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='update_emails_opt_out',
            field=models.BooleanField(default=False, help_text="Opt-out: don't send this customer occasional site update / new-set announcement emails. Doesn't affect order or account emails."),
        ),
    ]
