"""
Complete set mapping: DB set code -> TCGCSV group_id, pokemontcg.io set_id, Bulbapedia set name
"""

SET_MAPPING = {
    # DB code: (tcgcsv_group_id, ptcgio_set_id, bulba_set_name)
    # WotC Base
    "BS":       (604,   "base1",        "Base_Set"),
    "BS2":      (605,   "base4",        "Base_Set_2"),
    "FO":       (630,   "base3",        "Fossil_(TCG)"),
    "JU":       (635,   "base2",        "Jungle_(TCG)"),
    "SI1":      (648,   "si1",          "Southern_Islands_(TCG)"),
    "TR":       (1373,  "base5",        "Team_Rocket_(TCG)"),
    "G1":       (1441,  "gym1",         "Gym_Heroes_(TCG)"),
    "G2":       (1440,  "gym2",         "Gym_Challenge_(TCG)"),
    "N1":       (1396,  "neo1",         "Neo_Genesis_(TCG)"),
    "N2":       (1434,  "neo2",         "Neo_Discovery_(TCG)"),
    "N3":       (1389,  "neo3",         "Neo_Revelation_(TCG)"),
    "N4":       (1444,  "neo4",         "Neo_Destiny_(TCG)"),
    "LC":       (1374,  "base6",        "Legendary_Collection_(TCG)"),
    "BSS":      (1663,  None,           "Base_Set_(TCG)"),
    # EX Era
    "EX":       (1375,  "ecard1",       "Expedition_Base_Set_(TCG)"),
    "AQ":       (1397,  "ecard2",       "Aquapolis_(TCG)"),
    "SK":       (1372,  "ecard3",       "Skyridge_(TCG)"),
    "RS":       (1393,  "ex1",          "EX_Ruby_%26_Sapphire_(TCG)"),
    "SS":       (1392,  "ex2",          "EX_Sandstorm_(TCG)"),
    "DR":       (1376,  "ex3",          "EX_Dragon_(TCG)"),
    "MA":       (1377,  "ex4",          "EX_Team_Magma_vs_Team_Aqua_(TCG)"),
    "HL":       (1416,  "ex5",          "EX_Hidden_Legends_(TCG)"),
    "RG":       (1419,  "ex6",          "EX_FireRed_%26_LeafGreen_(TCG)"),
    "TRR":      (1428,  "ex7",          "EX_Team_Rocket_Returns_(TCG)"),
    "DX":       (None,  "ex8",          "EX_Deoxys_(TCG)"),
    "EM":       (1410,  "ex9",          "EX_Emerald_(TCG)"),
    "UF":       (1398,  "ex10",         "EX_Unseen_Forces_(TCG)"),
    "DS":       (1429,  "ex11",         "EX_Delta_Species_(TCG)"),
    "LM":       (1378,  "ex12",         "EX_Legend_Maker_(TCG)"),
    "HP":       (1379,  "ex13",         "EX_Holon_Phantoms_(TCG)"),
    "CG":       (1395,  "ex14",         "EX_Crystal_Guardians_(TCG)"),
    "DF":       (1411,  "ex15",         "EX_Dragon_Frontiers_(TCG)"),
    "PK":       (1383,  "ex16",         "EX_Power_Keepers_(TCG)"),
    # DP Era
    "DP":       (1430,  "dp1",          "Diamond_%26_Pearl_(TCG)"),
    "MT":       (1368,  "dp2",          "Mysterious_Treasures_(TCG)"),
    "SW":       (1380,  "dp3",          "Secret_Wonders_(TCG)"),
    "GE":       (1405,  "dp4",          "Great_Encounters_(TCG)"),
    "MD":       (1390,  "dp5",          "Majestic_Dawn_(TCG)"),
    "LA":       (1417,  "dp6",          "Legends_Awakened_(TCG)"),
    "SF":       (1369,  "dp7",          "Stormfront_(TCG)"),
    "PL":       (1406,  "pl1",          "Platinum_(TCG)"),
    "RR":       (1367,  "pl2",          "Rising_Rivals_(TCG)"),
    "SV":       (1384,  "pl3",          "Supreme_Victors_(TCG)"),
    "AR":       (1391,  "pl4",          "Arceus_(TCG)"),
    # HGSS
    "HS":       (1402,  "hgss1",        "HeartGold_%26_SoulSilver_(TCG)"),
    "UL":       (1399,  "hgss2",        "HS%E2%80%94Unleashed_(TCG)"),
    "UD":       (1403,  "hgss3",        "HS%E2%80%94Undaunted_(TCG)"),
    "TM":       (1381,  "hgss4",        "HS%E2%80%94Triumphant_(TCG)"),
    "CoL":      (1415,  "col1",         "Call_of_Legends_(TCG)"),
    # BW
    "BLW":      (1400,  "bw1",          "Black_%26_White_(TCG)"),
    "EPO":      (1424,  "bw2",          "Emerging_Powers_(TCG)"),
    "NVI":      (1385,  "bw3",          "Noble_Victories_(TCG)"),
    "NXD":      (1412,  "bw4",          "Next_Destinies_(TCG)"),
    "DEX":      (1386,  "bw5",          "Dark_Explorers_(TCG)"),
    "DRX":      (1394,  "bw6",          "Dragons_Exalted_(TCG)"),
    "DRV":      (1426,  "dv1",          "Dragon_Vault_(TCG)"),
    "BCR":      (1408,  "bw7",          "Boundaries_Crossed_(TCG)"),
    "PLS":      (1413,  "bw8",          "Plasma_Storm_(TCG)"),
    "PLF":      (1382,  "bw9",          "Plasma_Freeze_(TCG)"),
    "PLB":      (1370,  "bw10",         "Plasma_Blast_(TCG)"),
    "LTR":      (1409,  "bw11",         "Legendary_Treasures_(TCG)"),
    # XY
    "KSS":      (1522,  "xy0",          "Kalos_Starter_Set_(TCG)"),
    "XY":       (1387,  "xy1",          "XY_(TCG)"),
    "FLF":      (1464,  "xy2",          "Flashfire_(TCG)"),
    "FFI":      (1481,  "xy3",          "Furious_Fists_(TCG)"),
    "PHF":      (1494,  "xy4",          "Phantom_Forces_(TCG)"),
    "PRC":      (1509,  "xy5",          "Primal_Clash_(TCG)"),
    "DCR":      (1525,  "dc1",          "Double_Crisis_(TCG)"),
    "ROS":      (1534,  "xy6",          "Roaring_Skies_(TCG)"),
    "AOR":      (1576,  "xy7",          "Ancient_Origins_(TCG)"),
    "BKT":      (1661,  "xy8",          "BREAKthrough_(TCG)"),
    "BKP":      (1701,  "xy9",          "BREAKpoint_(TCG)"),
    "GEN":      (1728,  "g1",           "Generations_(TCG)"),
    "FCO":      (1780,  "xy10",         "Fates_Collide_(TCG)"),
    "STS":      (1815,  "xy11",         "Steam_Siege_(TCG)"),
    "EVO":      (1842,  "xy12",         "Evolutions_(TCG)"),
    # SM
    "SM01":     (1863,  "sm1",          "Sun_%26_Moon_(TCG)"),
    "SM02":     (1919,  "sm2",          "Guardians_Rising_(TCG)"),
    "SM03":     (1957,  "sm3",          "Burning_Shadows_(TCG)"),
    "SHL":      (2054,  "sm35",         "Shining_Legends_(TCG)"),
    "SM04":     (2071,  "sm4",          "Crimson_Invasion_(TCG)"),
    "SM05":     (2178,  "sm5",          "Ultra_Prism_(TCG)"),
    "SM06":     (2209,  "sm6",          "Forbidden_Light_(TCG)"),
    "CES":      (2278,  "sm7",          "Celestial_Storm_(TCG)"),
    "DRM":      (2295,  "sm75",         "Dragon_Majesty_(TCG)"),
    "SM8":      (2328,  "sm8",          "Lost_Thunder_(TCG)"),
    "SM9":      (2377,  "sm9",          "Team_Up_(TCG)"),
    "SM10":     (2420,  "sm10",         "Unbroken_Bonds_(TCG)"),
    "SM11":     (2464,  "sm11",         "Unified_Minds_(TCG)"),
    "HIF":      (2480,  "sm115",        "Hidden_Fates_(TCG)"),
    "HIFSV":    (2594,  "sma",          "Hidden_Fates_(TCG)"),
    "SM12":     (2534,  "sm12",         "Cosmic_Eclipse_(TCG)"),
    "SMP":      (1861,  "smp",          "SM_Black_Star_Promos_(TCG)"),
    # SWSH
    "SWSH01":   (2585,  "swsh1",        "Sword_%26_Shield_(TCG)"),
    "SWSH02":   (2626,  "swsh2",        "Rebel_Clash_(TCG)"),
    "SWSH03":   (2675,  "swsh3",        "Darkness_Ablaze_(TCG)"),
    "CHP":      (2685,  "swsh35",       "Champion%27s_Path_(TCG)"),
    "SWSH04":   (2701,  "swsh4",        "Vivid_Voltage_(TCG)"),
    "SHF":      (2754,  "swsh45",       "Shining_Fates_(TCG)"),
    "SHFSV":    (2781,  "swsh45sv",     "Shining_Fates_(TCG)"),
    "SWSH05":   (2765,  "swsh5",        "Battle_Styles_(TCG)"),
    "SWSH06":   (2807,  "swsh6",        "Chilling_Reign_(TCG)"),
    "SWSH07":   (2848,  "swsh7",        "Evolving_Skies_(TCG)"),
    "CLB":      (2867,  "cel25",        "Celebrations_(TCG)"),
    "CCC":      (2931,  "cel25c",       "Celebrations_(TCG)"),
    "SWSH08":   (2906,  "swsh8",        "Fusion_Strike_(TCG)"),
    "SWSH09":   (2948,  "swsh9",        "Brilliant_Stars_(TCG)"),
    "BRSTG":    (3020,  "swsh9tg",      "Brilliant_Stars_(TCG)"),
    "SWSH10":   (3040,  "swsh10",       "Astral_Radiance_(TCG)"),
    "ASRTG":    (3068,  "swsh10tg",     "Astral_Radiance_(TCG)"),
    "PGO":      (3064,  "pgo",          "Pok%C3%A9mon_GO_(TCG)"),
    "SWSH11":   (3118,  "swsh11",       "Lost_Origin_(TCG)"),
    "LORTG":    (3172,  "swsh11tg",     "Lost_Origin_(TCG)"),
    "SWSH12":   (3170,  "swsh12",       "Silver_Tempest_(TCG)"),
    "SITTG":    (17674, "swsh12tg",     "Silver_Tempest_(TCG)"),
    "CRZ":      (17688, "swsh12pt5",    "Crown_Zenith_(TCG)"),
    "CRZGG":    (17689, "swsh12pt5gg",  "Crown_Zenith_(TCG)"),
    "TK22":     (3179,  None,           "Trick_or_Trade_BOOster_Bundle_(TCG)"),
    "TK23":     (23266, None,           "Trick_or_Trade_BOOster_Bundle_(TCG)"),
    "TK24":     (23561, None,           "Trick_or_Trade_BOOster_Bundle_(TCG)"),
    # SV
    "SVP":      (22872, "svp",          "Scarlet_%26_Violet_Black_Star_Promos_(TCG)"),
    "SVI":      (22873, "sv1",          "Scarlet_%26_Violet_(TCG)"),
    "SVE":      (24382, "sve",          "Scarlet_%26_Violet_Energies_(TCG)"),
    "PAL":      (23120, "sv2",          "Paldea_Evolved_(TCG)"),
    "OBF":      (23228, "sv3",          "Obsidian_Flames_(TCG)"),
    "MEW":      (23237, "sv3pt5",       "Scarlet_%26_Violet%E2%80%94151_(TCG)"),
    "PAR":      (23286, "sv4",          "Paradox_Rift_(TCG)"),
    "PAF":      (23353, "sv4pt5",       "Paldean_Fates_(TCG)"),
    "TEF":      (23381, "sv5",          "Temporal_Forces_(TCG)"),
    "TWM":      (23473, "sv6",          "Twilight_Masquerade_(TCG)"),
    "SFA":      (23529, "sv6pt5",       "Shrouded_Fable_(TCG)"),
    "SCR":      (23537, "sv7",          "Stellar_Crown_(TCG)"),
    "SSP":      (23651, "sv8",          "Surging_Sparks_(TCG)"),
    "PRE":      (23821, "sv8pt5",       "Prismatic_Evolutions_(TCG)"),
    "JTG":      (24073, "sv9",          "Journey_Together_(TCG)"),
    "DRI":      (24269, "sv10",         "Destined_Rivals_(TCG)"),
    "BLK":      (24325, "zsv10pt5",     "Black_Bolt_(TCG)"),
    "WHT":      (24326, "rsv10pt5",     "White_Flare_(TCG)"),
    "PRIZEPACK":(22880, None,           "Prize_Pack_Series_(TCG)"),
    # MEG
    "MEG":      (24380, "me1",          "Mega_Evolution_(TCG)"),
    "PFL":      (24448, "me2",          "Phantasmal_Flames_(TCG)"),
    "MEP":      (24451, None,           "Mega_Evolution_Promos_(TCG)"),
    "MEE":      (24461, None,           "Mega_Evolution_Energies_(TCG)"),
    "ASC":      (24541, "me2pt5",       "Ascended_Heroes_(TCG)"),
    "POR":      (24587, "me3",          "Perfect_Order_(TCG)"),
    "CRI":      (24655, "me4",          "Chaos_Rising_(TCG)"),
    # McDonalds
    "MCD11":    (1401,  "mcd11",        "McDonald%27s_Collection_2011_(TCG)"),
    "MCD12":    (1427,  "mcd12",        "McDonald%27s_Collection_2012_(TCG)"),
    "MCD14":    (1692,  "mcd14",        "McDonald%27s_Collection_2014_(TCG)"),
    "MCD15":    (1694,  "mcd15",        "McDonald%27s_Collection_2015_(TCG)"),
    "MCD16":    (3087,  "mcd16",        "McDonald%27s_Collection_2016_(TCG)"),
    "MCD17":    (2148,  "mcd17",        "McDonald%27s_Collection_2017_(TCG)"),
    "MCD18":    (2364,  "mcd18",        "McDonald%27s_Collection_2018_(TCG)"),
    "MCD19":    (2555,  "mcd19",        "McDonald%27s_Collection_2019_(TCG)"),
    "MCD22":    (3150,  "mcd22",        "McDonald%27s_Collection_2022_(TCG)"),
}

if __name__ == '__main__':
    print(f"Total set mappings: {len(SET_MAPPING)}")
    # Verify all have tcgcsv group_id
    no_group = {k: v for k, v in SET_MAPPING.items() if not v[0]}
    print(f"Missing TCGCSV group_id: {list(no_group.keys())}")
    no_ptcgio = {k: v for k, v in SET_MAPPING.items() if not v[1]}
    print(f"Missing pokemontcg.io set_id: {list(no_ptcgio.keys())}")
