# Generated by Django 6.0.4 on 2026-08-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('sleeves', 'Card Sleeves'), ('deck_boxes', 'Deck Boxes'), ('storage_tins', 'Card Storage Tins'), ('life_counters', 'Life Counters'), ('playmats', 'Playmats'), ('protective_pages', 'Protective Pages'), ('storage_albums', 'Storage Albums'), ('collectible_storage', 'Collectible Storage'), ('supply_bundles', 'Supply Bundles'), ('supplies', 'Supplies'), ('other', 'Other')], default='other', max_length=30)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('tcgcsv_product_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('tcgcsv_category_id', models.IntegerField(blank=True, null=True)),
                ('tcgplayer_url', models.URLField(blank=True, max_length=500)),
                ('source_price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Accessories',
                'ordering': ['-created_at'],
            },
        ),
    ]
