# Generated by Django 6.0.4 on 2026-05-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_courier_name_order_courier_tracking_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='eft_confirmed',
            field=models.BooleanField(default=False, help_text='Tick when EFT payment received in bank account'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('payfast', 'PayFast'), ('eft', 'EFT / Bank Transfer'), ('coc', 'Cash on Collection')], default='payfast', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='pudo_locker_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='pudo_locker_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(blank=True, choices=[('collection', 'Cash on Collection'), ('pudo_locker', 'Pudo Kiosk-to-Locker'), ('pudo_door', 'Pudo Door-to-Door'), ('postnet', 'Postnet-to-Postnet')], default='pudo_locker', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Order Received'), ('pending_eft', 'Awaiting EFT Payment'), ('printed', 'Order Printed'), ('packed', 'Order Packed'), ('booked', 'Courier Booking'), ('ready', 'Ready for Collection'), ('collected', 'Courier Collected'), ('invoiced', 'Final Invoice'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordertracking',
            name='status',
            field=models.CharField(choices=[('pending', 'Order Received'), ('pending_eft', 'Awaiting EFT Payment'), ('printed', 'Order Printed'), ('packed', 'Order Packed'), ('booked', 'Courier Booking'), ('ready', 'Ready for Collection'), ('collected', 'Courier Collected'), ('invoiced', 'Final Invoice'), ('cancelled', 'Cancelled')], max_length=20),
        ),
    ]
