# Generated by Django 6.0.4 on 2026-05-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_eft_confirmed_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(blank=True, choices=[('collection', 'Cash on Collection'), ('pudo_locker', 'Pudo Locker-to-Locker'), ('pudo_kiosk', 'Pudo Locker-to-Kiosk'), ('pudo_medium', 'Pudo Medium/Tins Kiosk'), ('pudo_door', 'Pudo Locker-to-Door'), ('pudo_door', 'Pudo Door-to-Door'), ('postnet', 'Postnet-to-Postnet')], default='pudo_locker', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('awaiting_payment', 'Awaiting Payment'), ('pending', 'Order Received'), ('pending_eft', 'Awaiting EFT Payment'), ('printed', 'Order Printed'), ('packed', 'Order Packed'), ('booked', 'Courier Booking'), ('ready', 'Ready for Collection'), ('collected', 'Courier Collected'), ('invoiced', 'Final Invoice'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordertracking',
            name='status',
            field=models.CharField(choices=[('awaiting_payment', 'Awaiting Payment'), ('pending', 'Order Received'), ('pending_eft', 'Awaiting EFT Payment'), ('printed', 'Order Printed'), ('packed', 'Order Packed'), ('booked', 'Courier Booking'), ('ready', 'Ready for Collection'), ('collected', 'Courier Collected'), ('invoiced', 'Final Invoice'), ('cancelled', 'Cancelled')], max_length=20),
        ),
    ]
