# Generated by Django 6.0.4 on 2026-06-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_product_name_orderitem_product_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_confirmed',
            field=models.BooleanField(default=False, help_text="Manual check only — tick once you've personally verified this order was paid. Nothing automated reads this."),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_confirmed_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('eft', 'EFT'), ('payfast', 'PayFast')], help_text='Your own record of how payment actually came in.', max_length=20),
        ),
    ]
