# Generated by Django 6.0.4 on 2026-07-09 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_payment_confirmed_and_more'),
        ('products', '0021_pokemonproduct_prize_pack_series'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=50)),
                ('delivery_note', models.TextField(blank=True, help_text="Free-text delivery/collection info — address, Pudo locker, 'collection', etc.")),
                ('internal_note', models.TextField(blank=True, help_text='Not shown on the invoice — your own notes only.')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('eft_confirmed', models.BooleanField(default=False, help_text="Tick once you've personally verified the EFT payment landed. Nothing automated reads this.")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManualInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text='Card/item name.', max_length=500)),
                ('set_name', models.CharField(blank=True, max_length=255)),
                ('card_number', models.CharField(blank=True, max_length=20)),
                ('variant', models.CharField(blank=True, max_length=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text="Auto-filled from the linked product's current price on save. Editable at any time.", max_digits=10, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.manualinvoice')),
                ('product', models.ForeignKey(blank=True, help_text='Link a real catalog product to auto-pull its current price. Leave blank for off-site stock.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.pokemonproduct')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
