# Generated by Django 6.0.4 on 2026-07-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_manualinvoice_manualinvoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualinvoice',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage discount applied to the item subtotal (before shipping), e.g. 10 for 10%. Leave 0 for no discount.', max_digits=5),
        ),
    ]
