# Generated by Django 6.0.4 on 2026-07-19 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_buyorder_seller_note'),
        ('products', '0022_pokemonproduct_pos_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyorderitem',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Link a real catalog product if it matches one. Leave blank for anything off-catalog.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.pokemonproduct'),
        ),
    ]
