# Generated by Django 6.0.4 on 2026-07-28 12:48
# Hand-corrected: payment_confirmed -> cash_confirmed uses RenameField
# (preserves existing data via ALTER TABLE RENAME COLUMN) instead of the
# auto-generated RemoveField+AddField pair, which would have dropped every
# order's existing manual payment-confirmed tick and recreated the column
# blank. RenameField keeps the old help_text, so a follow-up AlterField
# updates it to the new Cash-on-Collection-specific wording.
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_invoice_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_confirmed',
            new_name='cash_confirmed',
        ),
        migrations.AlterField(
            model_name='order',
            name='cash_confirmed',
            field=models.BooleanField(default=False, help_text="Cash on Collection only — tick once you've personally verified payment was received in person."),
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_confirmed_method',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('awaiting_payment', 'Awaiting Payment'), ('pending', 'Order Received'), ('pending_eft', 'Awaiting EFT Payment'), ('printed', 'Order Printed'), ('packed', 'Order Packed'), ('booked', 'Courier Booking'), ('ready', 'Ready for Collection'), ('collected', 'Courier Collected'), ('invoiced', 'Complete'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordertracking',
            name='status',
            field=models.CharField(choices=[('awaiting_payment', 'Awaiting Payment'), ('pending', 'Order Received'), ('pending_eft', 'Awaiting EFT Payment'), ('printed', 'Order Printed'), ('packed', 'Order Packed'), ('booked', 'Courier Booking'), ('ready', 'Ready for Collection'), ('collected', 'Courier Collected'), ('invoiced', 'Complete'), ('cancelled', 'Cancelled')], max_length=20),
        ),
    ]
