# Generated by hand to match orders/models.py's Order.SHIPPING_CHOICES
# exactly (sandbox has no live DB/matching Django install to run
# makemigrations -- see products/migrations/0032_pokemonproduct_double_rare_rarity.py
# for the same situation earlier this session).
#
# Michael, 2026-09-18: "Please remove Postnet as option" -- drops
# "postnet" from the choices list going forward. Does NOT touch any
# existing Order rows that already used it (CharField choices aren't
# DB-enforced), so historical orders keep displaying fine.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_manualinvoice_more_statuses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(blank=True, choices=[('collection', 'Cash on Collection'), ('pudo_locker', 'Pudo Locker-to-Locker'), ('pudo_kiosk', 'Pudo Locker-to-Kiosk'), ('pudo_medium', 'Pudo Medium/Tins Kiosk'), ('pudo_door', 'Pudo Locker-to-Door'), ('pudo_door', 'Pudo Door-to-Door')], default='pudo_locker', max_length=20),
        ),
    ]
