# Generated by Django 6.0.4 on 2026-04-18 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Era',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='pokemonproduct',
            name='set_name',
        ),
        migrations.AddField(
            model_name='pokemonproduct',
            name='card_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemonproduct',
            name='gengar_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pokemonproduct',
            name='pb_id',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='pokemonproduct',
            name='pokedex_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemonproduct',
            name='sku',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='pokemonproduct',
            name='tcgplayer_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pokemonproduct',
            name='variant_override',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='pokemonproduct',
            name='card_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.cardset'),
        ),
        migrations.AddField(
            model_name='cardset',
            name='era',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sets', to='products.era'),
        ),
    ]
