# Generated by Django 6.0.4 on 2026-04-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_cardset_era_remove_pokemonproduct_set_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonproduct',
            name='flavour_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pokemonproduct',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
