# Generated by Django 6.0.4 on 2026-04-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_pokemonproduct_flavour_text_pokemonproduct_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardset',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='cardset',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardset',
            name='symbol_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='cardset',
            name='total_cards',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokemonproduct',
            name='artist',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pokemonproduct',
            name='attack_1_damage',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pokemonproduct',
            name='attack_1_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pokemonproduct',
            name='attack_1_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pokemonproduct',
            name='attack_2_damage',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pokemonproduct',
            name='attack_2_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pokemonproduct',
            name='attack_2_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pokemonproduct',
            name='hp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemonproduct',
            name='image_small_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='pokemonproduct',
            name='price_first_edition',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pokemonproduct',
            name='price_holo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pokemonproduct',
            name='price_normal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pokemonproduct',
            name='price_reverse_holo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pokemonproduct',
            name='resistance_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pokemonproduct',
            name='resistance_value',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='pokemonproduct',
            name='retreat_cost',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemonproduct',
            name='subtypes',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pokemonproduct',
            name='supertype',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pokemonproduct',
            name='weakness_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pokemonproduct',
            name='weakness_value',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
