# Generated by Django 6.0.4 on 2026-04-18 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_cardset_logo_url_cardset_release_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonproduct',
            old_name='subtypes',
            new_name='card_subtypes',
        ),
    ]
