# Generated by Django 6.0.4 on 2026-04-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_subtypes_pokemonproduct_card_subtypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonproduct',
            name='ability_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pokemonproduct',
            name='ability_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pokemonproduct',
            name='ability_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
