# Generated by Django 6.0.4 on 2026-04-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_pokemonproduct_ability_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonproduct',
            name='name_japanese',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
