# Generated by Django 6.0.4 on 2026-04-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_pokemonproduct_name_japanese'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonproduct',
            name='csv_sku',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pokemonproduct',
            name='rarity',
            field=models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('holo_rare', 'Holo Rare'), ('ultra_rare', 'Ultra Rare'), ('illustration_rare', 'Illustration Rare'), ('special_illustration_rare', 'Special Illustration Rare'), ('hyper_rare', 'Hyper Rare'), ('mega_hyper_rare', 'Mega Hyper Rare'), ('mega_attack_rare', 'Mega Attack Rare'), ('secret_rare', 'Secret Rare'), ('legendary', 'Legendary'), ('ace_spec', 'ACE SPEC'), ('gold_star', 'Gold Star'), ('shining', 'Shining')], default='common', max_length=30),
        ),
        migrations.AlterField(
            model_name='pokemonproduct',
            name='variant_override',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
