# Generated by Django 6.0.4 on 2026-04-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_pokemonproduct_csv_sku_alter_pokemonproduct_rarity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardset',
            name='checklist_pdf',
            field=models.FileField(blank=True, null=True, upload_to='checklists/'),
        ),
        migrations.AddField(
            model_name='cardset',
            name='checklist_xlsx',
            field=models.FileField(blank=True, null=True, upload_to='checklists/'),
        ),
    ]
