# Generated by Django 6.0.4 on 2026-05-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_cardset_checklist_pdf_cardset_checklist_xlsx'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonproduct',
            name='tcgcsv_product_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
