# Generated by Django 6.0.4 on 2026-05-20 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_ball_variant_prices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonproduct',
            name='price_rh_holo',
        ),
    ]
