# Generated by Django 6.0.4 on 2026-05-21 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_cardset_checklist_pdf_cardset_checklist_xlsx'),
        ('products', '0012_remove_pokemonproduct_price_rh_holo'),
    ]

    operations = [
    ]
