# Generated by Django 6.0.4 on 2026-05-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_merge_20260521_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonproduct',
            name='variant_sort',
            field=models.IntegerField(default=9),
        ),
    ]
