# Generated by Django 6.0.4 on 2026-05-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_pokemonproduct_variant_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardset',
            name='regulation_mark',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
