# Generated by Django 6.0.4 on 2026-05-28 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_cardset_regulation_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonproduct',
            name='legal_expanded',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemonproduct',
            name='legal_standard',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemonproduct',
            name='legal_unlimited',
            field=models.BooleanField(default=True),
        ),
    ]
