# Generated by Django 6.0.4 on 2026-06-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_pokemonproduct_legal_expanded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonproduct',
            name='number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
