# Generated by PokeBulk SA pipeline
# v1.0.0
# Adds tcgio_code and bulba_code fields to CardSet model

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_pokemonproduct_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardset',
            name='tcgio_code',
            field=models.CharField(
                max_length=20, blank=True, default='',
                help_text='pokemontcg.io API set code (e.g. swsh1). Used for API lookups only, never in filenames or paths.'
            ),
        ),
        migrations.AddField(
            model_name='cardset',
            name='bulba_code',
            field=models.CharField(
                max_length=20, blank=True, default='',
                help_text='Official Bulbapedia set abbreviation (e.g. SSH)'
            ),
        ),
    ]
