# Generated by Django 6.0.4 on 2026-06-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_cardset_tcgio_bulba_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonproduct',
            name='condition',
            field=models.CharField(choices=[('NM', 'Near Mint'), ('LP', 'Lightly Played'), ('MP', 'Moderately Played'), ('HP', 'Heavily Played'), ('DMG', 'Damaged')], default='NM', max_length=3),
        ),
        migrations.AlterField(
            model_name='cardset',
            name='bulba_code',
            field=models.CharField(blank=True, default='', help_text='Official Bulbapedia set abbreviation e.g. SSH', max_length=20),
        ),
        migrations.AlterField(
            model_name='cardset',
            name='tcgio_code',
            field=models.CharField(blank=True, default='', help_text='pokemontcg.io API set code e.g. swsh1. Used for API lookups only, never in filenames or paths.', max_length=20),
        ),
    ]
