# Generated by Django 6.0.4 on 2026-06-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_pokemonproduct_condition_alter_cardset_bulba_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonproduct',
            name='regulation_mark',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
