# Generated by Django 6.0.4 on 2026-06-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_pokemonproduct_regulation_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonproduct',
            name='prize_pack_series',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
