# Generated by Django 6.0.4 on 2026-07-30 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0022_pokemonproduct_pos_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_set', models.CharField(help_text="CardSet.code, e.g. 'ASC', 'TK22'", max_length=20)),
                ('card_key', models.CharField(help_text="Checklist item key, e.g. '001/217_N'", max_length=64)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='checklistentry',
            index=models.Index(fields=['user', 'card_set'], name='checklistentry_user_set_idx'),
        ),
        migrations.AddConstraint(
            model_name='checklistentry',
            constraint=models.UniqueConstraint(fields=('user', 'card_set', 'card_key'), name='unique_checklist_entry'),
        ),
    ]
