# Generated by Django 6.0.4 on 2026-07-30 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0023_checklistentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetCompletionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_set', models.CharField(help_text="CardSet.code, e.g. 'ASC', 'TK22'", max_length=20)),
                ('tier', models.CharField(choices=[('broke_base', 'Broke Base'), ('base_set', 'Base Set'), ('special_set_base', 'Special Set Base'), ('master_set', 'Master Set'), ('complete_set', 'Complete Set')], max_length=20)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='setcompletionevent',
            index=models.Index(fields=['card_set', 'tier'], name='setcompletionevent_set_tier_idx'),
        ),
        migrations.AddIndex(
            model_name='setcompletionevent',
            index=models.Index(fields=['-completed_at'], name='setcompletionevent_completed_idx'),
        ),
        migrations.AddConstraint(
            model_name='setcompletionevent',
            constraint=models.UniqueConstraint(fields=('user', 'card_set', 'tier'), name='unique_set_completion_event'),
        ),
    ]
