# Generated by Django 6.0.4 on 2026-08-02 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_setcompletionevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PokedexCollectionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='checklistentry',
            new_name='products_ch_user_id_5f0554_idx',
            old_name='checklistentry_user_set_idx',
        ),
        migrations.RenameIndex(
            model_name='setcompletionevent',
            new_name='products_se_card_se_c3fcf4_idx',
            old_name='setcompletionevent_set_tier_idx',
        ),
        migrations.RenameIndex(
            model_name='setcompletionevent',
            new_name='products_se_complet_22725f_idx',
            old_name='setcompletionevent_completed_idx',
        ),
        migrations.AddField(
            model_name='pokedexcollectionentry',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokedex_entries', to='products.pokemonproduct'),
        ),
        migrations.AddField(
            model_name='pokedexcollectionentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokedex_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='pokedexcollectionentry',
            index=models.Index(fields=['user'], name='products_po_user_id_d5b689_idx'),
        ),
        migrations.AddConstraint(
            model_name='pokedexcollectionentry',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_pokedex_entry'),
        ),
    ]
