# Generated by Django 6.0.4 on 2026-08-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_pokedexcollectionentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonproduct',
            name='pokedex_number_2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
