# Generated by Django 6.0.4 on 2026-09-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_era_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
