# Generated by Django 6.0.4 on 2026-09-03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_cardset_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('restock', 'Restock'), ('announcement', 'Announcement')], default='announcement', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, help_text='Optional extra detail shown under the title in the email.')),
                ('date', models.DateField(default=django.utils.timezone.localdate, help_text="Which month this counts toward in the monthly update email -- doesn't have to be today's date.")),
                ('link_url', models.URLField(blank=True, help_text="Optional link if this isn't about one specific product (e.g. the Community page).", max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, help_text='Optional -- link this to a specific product so the email can point straight at it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='products.pokemonproduct')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
