# Generated by Django 6.0.4 on 2026-09-03
# Michael, 2026-09-03: "dropdown for which set" on the staff Announcements
# form -- see SiteAnnouncement.card_set in products/models.py.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_siteannouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteannouncement',
            name='card_set',
            field=models.ForeignKey(blank=True, help_text='Optional -- which set this is about, if not a specific product. Used for the email link when no product is linked.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='products.cardset'),
        ),
        migrations.AlterField(
            model_name='siteannouncement',
            name='link_url',
            field=models.URLField(blank=True, help_text="Optional link if this isn't about one specific product or set (e.g. the Community page).", max_length=500),
        ),
    ]
