# Generated by Django 6.0.4 on 2026-09-11
# Michael, 2026-09-11: Pitch Black rarity cleanup -- added "double_rare" as
# its own PokemonProduct.RARITY_CHOICES entry, distinct from "ultra_rare".
# See products/models.py's RARITY_CHOICES comment and
# products/management/commands/sync_rarities_from_tcgcsv.py for the full
# story. Metadata-only change (choices aren't DB-enforced on a CharField),
# so no data migration is needed -- existing rows are untouched until
# sync_rarities_from_tcgcsv.py --apply is run.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_siteannouncement_card_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonproduct',
            name='rarity',
            field=models.CharField(
                choices=[
                    ('common', 'Common'),
                    ('uncommon', 'Uncommon'),
                    ('rare', 'Rare'),
                    ('holo_rare', 'Holo Rare'),
                    ('ultra_rare', 'Ultra Rare'),
                    ('double_rare', 'Double Rare'),
                    ('illustration_rare', 'Illustration Rare'),
                    ('special_illustration_rare', 'Special Illustration Rare'),
                    ('hyper_rare', 'Hyper Rare'),
                    ('mega_hyper_rare', 'Mega Hyper Rare'),
                    ('mega_attack_rare', 'Mega Attack Rare'),
                    ('secret_rare', 'Secret Rare'),
                    ('legendary', 'Legendary'),
                    ('ace_spec', 'ACE SPEC'),
                    ('gold_star', 'Gold Star'),
                    ('shining', 'Shining'),
                ],
                default='common',
                max_length=30,
            ),
        ),
    ]
