# Generated by hand to match products/models.py's BundleOpportunity exactly
# (sandbox has no live DB/matching Django install to run makemigrations --
# see products/migrations/0032_pokemonproduct_double_rare_rarity.py for the
# same situation earlier this session). Structure mirrors
# 0024_setcompletionevent.py, the closest existing precedent.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0032_pokemonproduct_double_rare_rarity'),
    ]

    operations = [
        migrations.CreateModel(
            name='BundleOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_set', models.CharField(help_text="CardSet.code, e.g. 'PBL', 'TT22'", max_length=20)),
                ('tier', models.CharField(choices=[('broke_base', 'Broke Base'), ('base_set', 'Base Set'), ('special_set_base', 'Special Set Base'), ('master_set', 'Master Set'), ('full_master', 'Full Master'), ('complete_set', 'Complete Set')], max_length=20)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bundle_opportunities_accepted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-accepted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bundleopportunity',
            index=models.Index(fields=['card_set', 'tier'], name='bundleopportunity_set_tier_idx'),
        ),
        migrations.AddConstraint(
            model_name='bundleopportunity',
            constraint=models.UniqueConstraint(fields=('card_set', 'tier'), name='unique_bundle_opportunity'),
        ),
    ]
