# Generated by Django 6.0.4 on 2026-09-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_bundleopportunity'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bundleopportunity',
            new_name='products_bu_card_se_c411bc_idx',
            old_name='bundleopportunity_set_tier_idx',
        ),
        migrations.AlterField(
            model_name='pokemonproduct',
            name='rarity',
            field=models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('holo_rare', 'Holo Rare'), ('ultra_rare', 'Ultra Rare'), ('double_rare', 'Double Rare'), ('illustration_rare', 'Illustration Rare'), ('special_illustration_rare', 'Special Illustration Rare'), ('hyper_rare', 'Hyper Rare'), ('mega_hyper_rare', 'Mega Hyper Rare'), ('mega_attack_rare', 'Mega Attack Rare'), ('secret_rare', 'Secret Rare'), ('legendary', 'Legendary'), ('ace_spec', 'ACE SPEC'), ('gold_star', 'Gold Star'), ('shining', 'Shining'), ('pikachu_rare', 'Pikachu Rare'), ('futuristic_rare', 'Futuristic Rare')], default='common', max_length=30),
        ),
    ]
